agent: Agent.class BlackMoves.class Data.class Game.class GameHistory.class GamePosition.class GameState.class Input.class Log.class OpeningBook.class Output1.class Output2.class Output3.class Output4.class Position.class ResultState.class State.class TimeSync.class WhiteMoves.class

run: Agent.class
	java Agent

newgame: TimeSync.class
	java TimeSync

Agent.class: Agent.java
	javac Agent.java

BlackMoves.class: BlackMoves.java
	javac BlackMoves.java

Data.class: Data.java
	javac Data.java

Game.class: Game.java
	javac Game.java

GameHistory.class: GameHistory.java
	javac GameHistory.java

GamePosition.class: GamePosition.java
	javac GamePosition.java

GameState.class: GameState.java
	javac GameState.java

Input.class: Input.java
	javac Input.java

Log.class: Log.java
	javac Log.java

OpeningBook.class: OpeningBook.java
	javac OpeningBook.java

Output1.class: Output1.java
	javac Output1.java

Output2.class: Output2.java
	javac Output2.java

Output3.class: Output3.java
	javac Output3.java

Output4.class: Output4.java
	javac Output4.java

Position.class: Position.java
	javac Position.java

ResultState.class: ResultState.java
	javac ResultState.java

State.class: State.java
	javac State.java

TimeSync.class: TimeSync.java
	javac TimeSync.java

WhiteMoves.class: WhiteMoves.java
	javac WhiteMoves.java
